cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	
	path("", views.get_cart, name="ver_carrito"),
	path("add/<product_id>/<quantity>/", views.add_to_cart, name="additem"),
	path("delete/<product_id>/", views.remove_from_cart, name="deleteitem"),

]

movart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from core import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('messages/', include("pinax.messages.urls", namespace="pinax_messages")),
    path('', include('core.urls', namespace="core")),
    path('', include('tienda.urls', namespace="tienda")),
    path('cart/', include('cart.urls', namespace="carrito")),
    path('fav/', include('favs.urls', namespace="favs")),
    path('denuncia/', include('denuncia.urls', namespace="denuncia")),
    path('evento/', include('evento.urls', namespace="evento")),
    path('reputacion/', include('reputacion.urls', namespace="reputacion")),
    path('transaccion/', include('transaccion.urls', namespace="transaccion")),
    path('impinstagram/', include('impinstagram.urls', namespace="impinstagram")),


]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tienda/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .views import ProductoDeleteView


app_name = 'tienda'

urlpatterns = [
	
	path("tienda/add/", views.tiendadd, name="tiendadd"),
	path("tienda/list/", views.tiendalist, name="tiendalist"),
	path("tienda/ver/<tid>/", views.tiendaver, name="tiendaver"),
	path("tienda/<tid>/prods/", views.prodlist, name="prodlist"),
	path("prod/<pid>/ver/", views.prodver, name="prodver"),
	path("prod/add/<url>/<img>/", views.prodadd, name="prodadd"),
	path("prod/<pid>/edit/", views.prodedit, name="prodedit"),
	path("prod/list/", views.prodlistall, name="prodlistall"),
	path("prod/<pid>/cons/", views.prodcons, name="prodcons"),
	path('prod/<pk>/delete/', ProductoDeleteView.as_view(), name="proddelete"),

]

transaccion/urls.py
from django.urls 	import path
from . 				import views


app_name = 'transaccion'

urlpatterns = [
	path('compras/', views.compras, name='compras'),
	path('ventas/', views.ventas, name='ventas'),
	path('add/<pid>/<q>/', views.add, name='add'),
	path('tracking/<trid>/', views.tracking, name='tracking'),
	path('cancelar/<trid>/', views.cancelar, name='cancelar'),
	path('suspender/<trid>/', views.suspender, name='suspender'),
	path('escalar/<trid>/', views.escalar, name='escalar'),
	#path('rem/<pid>/<q>/', views.rem, name='rem'),
]

tienda/models.py
from django.db import models
from django.conf import settings
from taggit.managers import TaggableManager


class Tienda(models.Model):
    usuario     = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,default=None) 
    estado      = models.PositiveIntegerField(default=1)

    def catalogo(self):
        return self.producto_set


class Producto(models.Model):
    tienda       = models.ForeignKey(Tienda, on_delete=models.CASCADE)
    nombre 	     = models.CharField(max_length=100)
    descripcion  = models.CharField(max_length=500)
    shortcode    = models.CharField(max_length=100)
    precio       = models.PositiveIntegerField()
    etiquetas    = TaggableManager()
    album        = models.BooleanField(default=False)
    visitas      = models.PositiveIntegerField(default=1)   

    class Meta:
        unique_together = ('tienda', 'shortcode')

    def visita(self):
        self.visitas += 1
        self.save()

    def save_album(self, urls):
        for url in urls:
            try:
                i = Imagen(producto=self, url=url)
                i.save()
            except Exception as e:
                raise e

    #def get_album(self):
                    


class Imagen(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    url = models.CharField(max_length=300)
    

transaccion/models.py
import datetime
from django.conf    import settings
from django.db      import models
from tienda.models  import Producto, Tienda


class Transaccion(models.Model):
	cliente     = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, default=None)
	producto    = models.ForeignKey(Producto, on_delete=models.CASCADE, default=None)
	tienda      = models.ForeignKey(Tienda, on_delete=models.CASCADE, default=None)
	cantidad    = models.PositiveIntegerField(default=1)
	precio      = models.PositiveIntegerField(default=1)
	fecha       = models.DateField(default=datetime.date.today)
	estado_act 	= models.PositiveIntegerField(default=1)

	def __str__(self):
		return self.cliente.username

	def guardar(self):
		self.save()
		return self


class Movimiento(models.Model):
	ENPROGRESO  = 1
	CONFIRMADO  = 2
	RETIRAR     = 3
	RECIBIDO    = 4
	CANCELADO   = 5
	SUSPENDIDO   = 6
	ESTADO = (
		(ENPROGRESO, 'En progreso'),
		(CONFIRMADO, 'Confirmado'),
		(RETIRAR, 'Retirar'),
		(RECIBIDO, 'Recibido'),
		(CANCELADO, 'Cancelado'),
		(SUSPENDIDO, 'Suspendido'),
	)
	transaccion = models.ForeignKey(Transaccion, on_delete=models.CASCADE, default=None)    
	estado      = models.PositiveSmallIntegerField( choices=ESTADO, default=ENPROGRESO ,)
	fecha       = models.DateField(default=datetime.date.today)

	class Meta:
		ordering = ('-fecha',)
	
	def __str__(self):
		return self.get_estado_display()

	def suspender(self):
		self.estado = 6
		self.transaccion.estado_act = self.estado
		self.transaccion.guardar()
		self.save()
		return self

	def cancelar(self):
		self.estado = 5
		self.transaccion.estado_act = self.estado
		self.transaccion.guardar()
		self.save()
		return self

	def escalar(self):
		if self.estado <= 4:
			self.estado = self.estado + 1
			self.transaccion.estado_act = self.estado
			self.transaccion.guardar()			
			self.save()
		return self

transaccion/forms.py
from django.forms import ModelForm
from django import forms

from .models import Transaccion, Movimiento


class TransaccionForm(ModelForm):
	class Meta:
		model = Transaccion
		fields = ['cantidad']


class MovimientoForm(ModelForm):
    class Meta:
        model = Movimiento
        fields = ['estado']

transaccion/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models 		import Transaccion, Movimiento
from .forms 		import TransaccionForm
from tienda.models  import Producto, Tienda


@login_required
def compras(request):
	try:
		ts = Transaccion.objects.filter(cliente=request.user)
	except Exception as e:
		messages.error(request, e)
		ts = {} 		
	return render(request, 'transaccion/compras.html', {'ts' : ts})


@login_required
def ventas(request):
	try:
		tienda = Tienda.objects.get(usuario=request.user)
		ts = Transaccion.objects.filter(tienda=tienda).exclude(estado_act=1)
	except Exception as e:
		messages.error(request, e)
		ts = {} 			
	return render(request, 'transaccion/ventas.html', {'ts' : ts})


@login_required
def add(request, pid, q):
	try:
		producto 	= Producto.objects.get(id=pid)
		tienda 		= producto.tienda
		cliente     = request.user
		t           = Transaccion(cliente=request.user, 
										producto=producto, 
										tienda=producto.tienda,
										precio=producto.precio,
										cantidad = q )
		t.save()
		mov = Movimiento(transaccion=t)
		mov.save()
		messages.success(request, 'Se ha realizado correctamente!')
		return HttpResponseRedirect('/transaccion/compras')   
	except Exception as e:
		messages.error(request, e)         
	return HttpResponseRedirect('/transaccion/compras')


@login_required
def tracking(request, trid):
	try:
		movs = Movimiento.objects.filter(transaccion=trid)
	except Exception as e:
		messages.error(request, e) 
	return render(request, 'transaccion/tracking.html', {'movs' : movs})


@login_required
def cancelar(request, trid):
	try:
		tr 	= Transaccion.objects.get(id=trid)
		mov = Movimiento(transaccion=tr)
		mov.cancelar()
	except Exception as e:
		messages.error(request, e) 
	return HttpResponseRedirect('/transaccion/compras')	


@login_required
def suspender(request, trid):
	try:
		tr 	= Transaccion.objects.get(id=trid)
		mov = Movimiento(transaccion=tr)
		mov.suspender()
	except Exception as e:
		messages.error(request, e) 
	return HttpResponseRedirect('/transaccion/compras')		


@login_required
def escalar(request, trid):
	try:
		tr 	= Transaccion.objects.get(id=trid)
		mov = Movimiento(transaccion=tr, estado=tr.estado_act)
		mov.escalar()
		messages.success(request, 'Se ha realizado con éxito!') 
	except Exception as e:
		messages.error(request, e) 
	url = request.META.get('HTTP_REFERER')
	return redirect(url)	

templates/transaccion/compras.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}
<h3>Compras realizadas</h3>


<div class="table-responsive">
<table class="table table-hover ">
        <thead class="thead-light">
            <tr>
            	<th scope="col">Tracking</th>
                <th scope="col">Tienda</th>
                <th scope="col">Producto</th>
                <th scope="col">Precio</th>
                <th scope="col">Estado</th>
                <th scope="col">Accción</th>
            </tr>
        </thead>
        <tbody>
            {% for t in ts %}
            <tr>
            	<td>
                <a href="{% url 'transaccion:tracking' t.id %}">
                    {{t.id}}
                </a>
                </td>
                <td>
                <a href="{% url 'tienda:tiendaver' t.producto.tienda.id %}">
                    {{t.producto.tienda.usuario.username}}
                </a>
                </td>
                <td>
                <a href="{% url 'tienda:prodver' t.producto.id %}">
                    {{t.producto.nombre}}
                </a>
                </td>
                <td>{{t.precio}}</td>
                <td>{{ t.estado_act }}</td>
                <td>               
                    {% if t.estado_act == 1%}
                    <a href="{% url 'transaccion:escalar' t.id %}" class="btn btn-sm btn-primary" onclick="confirm('Confirma?');">
                        <i class="fas fa-check-circle"></i> Confirmar
                    </a>                
                    {% elif t.estado_act == 3%}
                    <a href="{% url 'transaccion:escalar' t.id %}" class="btn btn-sm btn-success" onclick="confirm('Confirma?');">
                        <i class="fas fa-check-circle"></i> Recibido
                    </a>
                    {% elif t.estado_act == 4%}
                    {% else %}
                    <span class="badge badge-pill badge-secondary">
                        Espera de la tienda
                    </span>
                    {% endif %}                     
                    <!--<a href="{% url 'transaccion:suspender' t.id %}" class="btn btn-sm btn-warning" onclick="confirm('Confirma?');">
                        <i class="fas fa-pause"></i>
                    </a>
                    <a href="{% url 'transaccion:cancelar' t.id %}" class="btn btn-sm btn-danger" onclick="confirm('Confirma?');">
                        <i class="fas fa-window-close"></i>
                    </a>-->                    
                </td>
            </tr>
            {% endfor %}
        </tbody>
</table>
</div>

{% endblock %}

templates/transaccion/tracking.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}
<h3>Tracking de compra</h3>

<table class="table table-hover">
    <tr>
        <thead class="thead-light">
            <tr>
                <th scope="col">id</th>
                <th scope="col">Cliente</th>
                <th scope="col">Producto</th>
                <th scope="col">Cantidad</th>
                <th scope="col">Estado</th>
            </tr>
        </thead>
        <tbody>
            {% for mov in movs %}
            <tr>
                <td>{{mov.id}}</td>
                <td>{{mov.transaccion.cliente}}</td>
                <td>
                    <a href="{% url 'tienda:prodver' mov.transaccion.producto.id %}">
                        {{mov.transaccion.producto.nombre}}
                    </a>                </td>
                <td>{{mov.transaccion.cantidad}}</td>
                <td>{{ mov.get_estado_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
</table>


{% endblock %}

templates/transaccion/ventas.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}
<h3>Ventas realizadas</h3>

<div class="table-responsive">
<table class="table table-hover ">
        <thead class="thead-light">
            <tr>
                <th scope="col">Tracking</th>
                <th scope="col">Cliente</th>
                <th scope="col">Producto</th>
                <th scope="col">Cantidad</th>
                <th scope="col">Estado</th>
                <th scope="col">Acción</th>
            </tr>
        </thead>
        <tbody>
            {% for t in ts %}
            <tr>
                <td>
                <a href="{% url 'transaccion:tracking' t.id %}">
                    {{t.id}}
                </a>
                </td>
                <td>
                    <a href="{% url 'tienda:tiendaver' t.cliente.id %}">{{t.cliente}}
                    </a>  
                </td>
                <td>
                    <a href="{% url 'tienda:prodver' t.producto.id %}">
                        {{t.producto.nombre}}
                    </a>                
                </td>
                <td>{{t.cantidad}}</td>
                <td>{{ t.estado_act }}</td>
                <td>
                {% if t.estado_act == 2%}
                    <a href="{% url 'transaccion:escalar' t.id %}" class="btn btn-sm btn-success" onclick="confirm('Confirma?');">
                        <i class="fas fa-box"></i> Retirar
                    </a>                
                {% endif %}                     
                </td>
            </tr>
            {% endfor %}
        </tbody>
</table>
</div>

{% endblock %}