cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	
	path("", views.get_cart, name="ver_carrito"),
	path("add/<product_id>/<quantity>/", views.add_to_cart, name="additem"),
	path("delete/<product_id>/", views.remove_from_cart, name="deleteitem"),

]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [

	path("logout/", auth_views.LogoutView.as_view(), name="logout"),
	path("", views.home, name="home"),
	path("login/", views.login, name="login"),
	path("privacy/", views.privacy, name="privacy"),
	path("nosotros/", views.nosotros, name="nosotros"),
	path("verificar_perfil/", views.verificar_perfil, name="verificar_perfil"),
	path("actualizar_perfil/", views.actualizar_perfil, name="actualizar_perfil"),
	path("ver_perfil/", views.ver_perfil, name="ver_perfil"),

]

denuncia/urls.py
from django.urls 	import path
from . 				import views
from .views import (DenunciaDelete)

app_name = 'denuncia'

urlpatterns = [
	path('list/', views.dlist, name='dlist'),
	path('add/<pid>', views.dadd, name='dadd'),
	path('delete/<int:pk>/', DenunciaDelete.as_view(), name='delete'),
]

evento/urls.py
from django.urls 	import path

from .views import (
    EventoList,
    EventoDetail,
    EventoCreation,
    EventoUpdate,
    EventoDelete
)

app_name = 'evento'

urlpatterns = [

    path('list/', EventoList.as_view(), name='list'),
    path('ver/<int:pk>/', EventoDetail.as_view(), name='detail'),
    path('add/', EventoCreation.as_view(), name='add'),
    path('edit/<int:pk>/', EventoUpdate.as_view(), name='edit'),
    path('delete/<int:pk>/', EventoDelete.as_view(), name='delete'),

]

favs/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'favs'

urlpatterns = [
	
	#Productos favoritos
	path("p/list/", views.plist, name="plist"),
	path("p/<pid>/add/", views.padd, name="padd"),
	path("p/<pid>/remove/", views.premove, name="premove"),

	#Tiendas favoritas
	path("t/list/", views.tlist, name="tlist"),
	path("t/<tid>/add/", views.tadd, name="tadd"),
	path("t/<tid>/remove/", views.tremove, name="tremove"),	

]

movart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from core import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('messages/', include("pinax.messages.urls", namespace="pinax_messages")),
    path('', include('core.urls', namespace="core")),
    path('', include('tienda.urls', namespace="tienda")),
    path('cart/', include('cart.urls', namespace="carrito")),
    path('fav/', include('favs.urls', namespace="favs")),
    path('denuncia/', include('denuncia.urls', namespace="denuncia")),
    path('evento/', include('evento.urls', namespace="evento")),
    path('reputacion/', include('reputacion.urls', namespace="reputacion")),
    path('transaccion/', include('transaccion.urls', namespace="transaccion")),
    path('impinstagram/', include('impinstagram.urls', namespace="impinstagram")),


]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tienda/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .views import ProductoDeleteView


app_name = 'tienda'

urlpatterns = [
	
	path("tienda/add/", views.tiendadd, name="tiendadd"),
	path("tienda/list/", views.tiendalist, name="tiendalist"),
	path("tienda/ver/<tid>/", views.tiendaver, name="tiendaver"),
	path("tienda/<tid>/prods/", views.prodlist, name="prodlist"),
	path("prod/<pid>/ver/", views.prodver, name="prodver"),
	path("prod/add/<url>/<img>/", views.prodadd, name="prodadd"),
	path("prod/<pid>/edit/", views.prodedit, name="prodedit"),
	path("prod/list/", views.prodlistall, name="prodlistall"),
	path("prod/<pid>/cons/", views.prodcons, name="prodcons"),
	path('prod/<pk>/delete/', ProductoDeleteView.as_view(), name="proddelete"),

]

core/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Perfil(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) 
    url_profile_picture = models.CharField(max_length=500, default=None)
    domicilio 	= models.CharField(max_length=100, default=None, null=True)
    descripcion = models.CharField(max_length=250, default=None, null=True)
    telefono    = models.CharField(max_length=50, default=None, null=True)
    

core/forms.py
from django.forms import ModelForm
from .models import Perfil


class PerfilForm(ModelForm):
	class Meta:
		model   = Perfil
		fields  = ['url_profile_picture', 'domicilio','telefono', 'descripcion']
		

core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Perfil
from .forms  import PerfilForm       


def home(request):
	return render(request, 'core/home.html')

def login(request):
	return render(request, 'core/login.html')

def privacy(request):
	return render(request, 'core/privacy.html')


def nosotros(request):
	return render(request, 'core/nosotros.html')

# Luego de realizarse correctamente el registro del nuevo usuario,
# creamos y asignamos un Perfil con los datos personales
def verificar_perfil(request):
	if request.user is not None:
		try:
			perfil = Perfil.objects.get(usuario=request.user)
		except Exception as e:
			perfil = None
		#si el perfil no existe es porque es un usuario nuevo
		if perfil is None:
			perfil = Perfil()
			perfil.usuario = request.user
			perfil.url_profile_picture = 'https://images-na.ssl-images-amazon.com/images/I/51XYolCzVKL._SL1200_.jpg'
			try:
				perfil.save()
				messages.success(request, 'Login perfecto')
			except Exception as e:
				messages.error(request, e)
	return render(request, 'core/home.html')


def actualizar_perfil(request):
	try:
		perfil = Perfil.objects.get(usuario=request.user)
	except Exception as e:
		messages.error(request, e)

	if request.method == 'POST':
		form = PerfilForm(request.POST,instance=perfil)
		if form.is_valid():
			try:
				form.save()
				messages.success(request, 'Se ha editado con éxito!')
				return redirect('/')
			except Exception as e:
				messages.error(request, e)
			
	else:
		form = PerfilForm(instance=perfil)
	return render(request, 'core/perfiled.html', {'form': form})


def ver_perfil(request):
	try:
		perfil = Perfil.objects.get(usuario=request.user)
	except Exception as e:
		messages.error(request, e)
		return redirect('/')
	return render(request, 'core/perfilver.html', {'perfil': perfil})
	

templates/core/footer.html
<footer class="footer-basic-centered">

      <p class="footer-company-motto">MovArt</p>

      <p class="footer-links">
          <a href="{% url 'tienda:tiendalist' %}">Tiendas</a>
        ·
        <a href="{% url 'tienda:prodlistall' %}">Productos</a>
        ·
        <a href="{% url 'core:nosotros' %}">Nosotros</a>
        ·
        <a href="{% url 'core:privacy' %}">Políticas de privacidad</a>
        ·
        <a href="{% url 'evento:list' %}">Eventos</a>

      </p>

      <p class="footer-company-name">MovArt © 2019</p>

    </footer>

templates/core/home.html
<!-- user.html -->

{% extends 'base/base_home.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}

<div class="container-fluid">

<div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'img/bannerppal.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/landback3.png' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/banner2.jpeg' %}" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="categoria fuente">
	<div class="division"></div>
	<h2 class="textcat">Novedades</h2>
	<div class="division"></div>
</div>


<div class="jumbotron jumbotron-fluid bg-dark sabermas">
  <div class="container-fluid">
    <p class="lead">	Somos una tienda virtual Argentina destinada a promover el mercado Artesanal nacional.Somos una tienda virtual Argentina destinada a promover el mercado Artesanal nacional.Somos una tienda virtual Argentina destinada a promover el mercado Artesanal nacional.
    </p>
    <div class="col-md-2 col-sm-4 offset-md-5 offset-sm-5">
    <button href="#" type="button" class="btn btn-light btn-block rounded-pill">Conocenos</button>
    </div>
  </div>
</div>

<div class="row text-center tutorial color-bordo">
	<div class="col-4">
		<span">
			<h1><i class="fa fa-gift fa-2x" aria-hidden="true"></i></h1>
		</span>
		<h5>Te gusta?</h5>
	</div>
	<div class="col-4">
		<span>
			<h1><i class="fa fa-handshake-o fa-2x" aria-hidden="true"></i></h1>
		</span>
		<h5>Coordina</h5>
	</div>
	<div class="col-4">
		<span>
			<h1><i class="fas fa-laugh-beam fa-2x"></i></h1>
		</span>
		<h5>¡¡Disfruta!!</h5>
	</div>
</div>

<div class="categoria fuente">
	<div class="division"></div>
	<h2 class="textcat">Productos</h2>
	<div class="division"></div>
</div>

<div id="productos" class="carousel slide carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#productos" data-slide-to="0" class="active"></li>
    <li data-target="#productos" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner carousel-productos">
    <div class="carousel-item active">
	    <div class="row">
	      <div class="col"><img src="{% static 'img/1.jpeg' %}" class="d-block w-100 img-thumbnail" alt="..."></div> 
	      <div class="col"><img src="{% static 'img/2.jpeg' %}" class="d-block w-100 img-thumbnail" alt="..."></div>
	      <div class="col"><img src="{% static 'img/3.jpeg' %}" class="d-block w-100 img-thumbnail" alt="..."></div>
	      <div class="col"><img src="{% static 'img/4.jpeg' %}" class="d-block w-100 img-thumbnail" alt="..."></div>
      </div>
	</div>
    <div class="carousel-item">
	    <div class="row">
	      <div class="col"><img src="{% static 'img/1.jpeg' %}" class="d-block w-100 img-thumbnail" alt="..."></div>
	      <div class="col"><img src="{% static 'img/2.jpeg' %}" class="d-block w-100 img-thumbnail" alt="..."></div>
	      <div class="col"><img src="{% static 'img/3.jpeg' %}" class="d-block w-100 img-thumbnail" alt="..."></div>
	      <div class="col"><img src="{% static 'img/4.jpeg' %}" class="d-block w-100 img-thumbnail" alt="..."></div>
	    </div>
	</div>	
  </div>
  <a class="carousel-control-prev" href="#productos" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#productos" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

</div>
{% endblock %}

templates/core/login.html
<!-- templates/login.html -->

{% extends 'base/base.html' %}
{% load static %}
{% block title %}  {% endblock %}
{% block content %}
<div class="login">
<div class="row justify-content-md-center">
    <div class="col col-lg-2"></div>
    
    <div class="col-md-auto card">
        <div class="text-center card-body">
            <div class="form-signin">
              <img src="{% static 'img/logo.png' %}" width="200" class="d-inline-block align-top">
              <p></p>
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                    </div>
                    <div class="panel-body">
                        <form role="form" action="{% url 'login' %}" method="post">
                          {% csrf_token %}
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Ingrese usuario" name="username" type="user" autofocus="">
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Contraseña" name="password" type="password" value="">
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <button type="submit" class="btn btn-sm btn-success">Ingresar</button>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </br></br>
              <a class="item" href="{% url 'core:privacy' %}">Políticas de privacidad</a>
            </div>
        </div>
    </div>

    <div class="col col-lg-2"></div>
</div>
</div>
{% endblock %}

templates/core/menu.html
{% load static %}
{% load pinax_messages_tags %}

<nav class="navbar navbar-expand-lg navbar-light bg-light mymenu">
  <a class="navbar-brand" href="{% url 'core:home' %}">
    <img src="{% static 'img/logo.png' %}" width="200" class="d-inline-block align-top" alt="">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-shopping-cart"></i> comprar
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'tienda:tiendalist' %}">Buscar Tiendas</a>
          <a class="dropdown-item" href="{% url 'tienda:prodlistall' %}">Buscar Productos</a>
          <a class="dropdown-item" href="{% url 'transaccion:compras' %}">Compras</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-money"></i> vender
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <!--<a class="dropdown-item" href="{% url 'tienda:tiendadd' %}">Publicar Tienda</a>-->
          <a class="dropdown-item" href="{% url 'impinstagram:feed' %}">Publicar de Instagram</a>
          <a class="dropdown-item" href="{% url 'transaccion:ventas' %}">Ventas</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:nosotros' %}"><i class="fa fa-info-circle"></i> nosotros</a>
      </li>

      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'denuncia:dlist' %}">
          <i class="fas fa-bullhorn"></i> 
          denuncias</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'evento:list' %}">
          <i class="fa fa-calendar" aria-hidden="true"></i> 
          eventos</a>
      </li>

      {% with user|unread_thread_count as user_unread %}
      <li class="{% if user_unread %}{% endif %} nav-item">
          <a href="{% url 'pinax_messages:inbox' %}" class="nav-link" >
              <i class="fa fa-envelope"></i>
              {% if user_unread %}
                <span class="badge badge-pill badge-warning">
                {{ user_unread }}
                </span> 
              {% endif %}
          </a>
      </li>        
      {% endwith %}  

      <li class="nav-item">
      <a class="nav-link" href="{% url 'favs:plist' %}">
        <i class="fa fa-heart"></i>
      </a>
      </li>
      <li class="nav-item">
      <a class="nav-link" href="{% url 'favs:tlist' %}">
        <i class="fa fa-star"></i>
      </a>         
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ request.user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="nav-link" href="{% url 'core:ver_perfil' %}">
            <i class="fa fa-user"></i> Mis Datos
          </a>                 
          <a class="nav-link" href="{% url 'core:logout' %}">
            <i class="fa fa-sign-out-alt"> </i>Salir
          </a>
        </div>
      </li>
      <li class="nav-item">
          
      </li>
      {% else %}
      <li class="nav-item">
          <a class="nav-link" href="{% url 'core:login' %}">LOGIN</a>
      </li>
      {% endif %}
      
    </ul>
  </div>
</nav>

templates/core/nosotros.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}  {% endblock %}
{% block content %}
<div class="jumbotron bg-dark sabermas">
  <div class="container-fluid">
    <div class="col-md-2 col-sm-4 offset-md-5 offset-sm-5 ">
    <button href="#" type="button" class="btn btn-light btn-block rounded-pill mb-5">Nosotros</button>
    </div>
    <p class="lead">    Somos una tienda virtual Argentina destinada a promover el mercado Artesanal nacional.Somos una tienda virtual Argentina destinada a promover el mercado Artesanal nacional.Somos una tienda virtual Argentina destinada a promover el mercado Artesanal nacional.
    </p>
    <p class="lead"> 
      El equipo de MovArt se encuentra a tu disposición para ayudarte.
      Comunícate con nosotros a cualquiera de los siguientes medios de contacto:
    </p>
    <ul class="list-group">
      <li class="list-group-item">WhatsApp: 0362-154119163</li>
      <li class="list-group-item">Correo electrónico: soporte@movart.herokuapp.com</li>
      <li class="list-group-item">Redes Sociales: @movart</li>
    </ul>

    <div class="card mt-5">
      <div class="card-body">
        
        <div class="text-center h2">Proyecto Final ISI 2019</div>
        <p class="text-dark">Docentes</p>
          <ul>
            <li>Ing. Graciela Méndez</li>
            <li>Dr. César Javier Acuña</li>
          </ul>
          <p class="text-dark">Integrantes</p>
          <ul>
              <li>Agoston, Marcelo</li>
              <li>García, Belén</li>
              <li>Hruza, Gabriel Carlos</li>
              <li>Moore, Walter</li>
          </ul>
        </div>
    </div>
  </div>



</p>
  </div>
</div>
{% endblock%}

templates/core/perfiled.html
{% extends 'base/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}{% endblock %}
{% block content %}

<div class="mb-3">
	<h3>Completa el formulario</h3>
</div>

<form method="post" class="ui form {% if form.errors %}error{% endif %}" novalidate>
{% csrf_token %}

<div class="card">
	<div class="row">
	
	<aside class="col-sm-5 text-center mt-3">
	<img class="img-fluid w-50 rounded-circle" src="{{ form.instance.url_profile_picture }}" alt="card image">
	</aside>

	<aside class="col-sm-7">

	<article class="card-body p-5">	
	<div class="form-group row"> 
		<label class="col-sm-3 col-form-label">Foto Perfil:</label>
		<div class="col-sm-9">
			{% render_field form.url_profile_picture class+="form-control" %}
		{% if form.url_profile_picture.errors %}
	    	<div class="text-danger">
	    		{{ form.url_profile_picture.errors }}
	    	</div>
	    {% endif %}
	    </div>
	</div>

	<div class="form-group row"> 
		<label class="col-sm-3 col-form-label">Domicilio:</label>
		<div class="col-sm-9">
			{% render_field form.domicilio class+="form-control" placeholder=form.domicilio.label %}
		{% if form.domicilio.errors %}
	    	<div class="text-danger">
	    		{{ form.domicilio.errors }}
	    	</div>
	    {% endif %}
	    </div>
	</div>

	<div class="form-group row"> 
		<label class="col-sm-3 col-form-label">Teléfono:</label>
		<div class="col-sm-9">
			{% render_field form.telefono class+="form-control" placeholder=form.telefono.label%}
		{% if form.telefono.errors %}
	    	<div class="text-danger">
	    		{{ form.telefono.errors }}
	    	</div>
	    {% endif %}
	    </div>
	</div>

	<div class="form-group row"> 
		<label class="col-sm-3 col-form-label">Descripción:</label>
		<div class="col-sm-9">
			{% render_field form.descripcion class+="form-control" placeholder=form.descripcion.label%}
		{% if form.descripcion.errors %}
	    	<div class="text-danger">
	    		{{ form.descripcion.errors }}
	    	</div>
	    {% endif %}
	    </div>
	</div>

	<div class="text-center">
	<div class="text-center">
		<button type="submit" class="btn btn-warning"> 
			<i class="fa fa-check"></i> Enviar </button>
		<a role="button" href="{% url 'core:home' %}" class="btn btn-light">
		<i class="fa fa-times"></i> Volver </a>
	</div>
	</div>

	</article> <!-- card-body.// -->
	</aside> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
</form>
{% endblock %}

templates/core/perfilver.html
{% extends 'base/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}{% endblock %}
{% block content %}

<div class="mb-3">
	<h3>Datos de la Tienda</h3>
</div>

<div class="card">
	<div class="row">
	
	<aside class="col-sm-5 text-center mt-1">
	<img class="img-fluid w-50 rounded-circle" src="{{ perfil.url_profile_picture }}" alt="card image">
	</aside>

	<aside class="col-sm-7">

	<article class="card-body p-5">	

	<div class="perfil-group row"> 
		<label class="col-sm-12 col-perfil-label">Domicilio:{{ perfil.domicilio }}</label>
	</div>

	<div class="perfil-group row"> 
		<label class="col-sm-12 col-perfil-label">Teléfono:{{ perfil.telefono }}</label>
	</div>

	<div class="perfil-group row"> 
		<label class="col-sm-12 col-perfil-label">Descripción: {{ perfil.descripcion }}</label>
	</div>

	{% if user.is_authenticated %}
	{% ifequal perfil.usuario user %}
	<div class="text-center">
		<a role="button" href="{% url 'core:actualizar_perfil' %}" class="btn btn-warning"> 
			<i class="fa fa-edit"></i> Editar </a>
		<a role="button" href="{% url 'core:home' %}" class="btn btn-light">
		<i class="fa fa-times"></i> Cancelar </a>
	</div>
	{% endifequal %}
	{% endif %}
	
	</article> <!-- card-body.// -->
	</aside> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
</perfil>

{% endblock %}