cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	
	path("", views.get_cart, name="ver_carrito"),
	path("add/<product_id>/<quantity>/", views.add_to_cart, name="additem"),
	path("delete/<product_id>/", views.remove_from_cart, name="deleteitem"),

]

evento/urls.py
from django.urls 	import path

from .views import (
    EventoList,
    EventoDetail,
    EventoCreation,
    EventoUpdate,
    EventoDelete
)

app_name = 'evento'

urlpatterns = [

    path('list/', EventoList.as_view(), name='list'),
    path('ver/<int:pk>/', EventoDetail.as_view(), name='detail'),
    path('add/', EventoCreation.as_view(), name='add'),
    path('edit/<int:pk>/', EventoUpdate.as_view(), name='edit'),
    path('delete/<int:pk>/', EventoDelete.as_view(), name='delete'),

]

movart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from core import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('messages/', include("pinax.messages.urls", namespace="pinax_messages")),
    path('', include('core.urls', namespace="core")),
    path('', include('tienda.urls', namespace="tienda")),
    path('cart/', include('cart.urls', namespace="carrito")),
    path('fav/', include('favs.urls', namespace="favs")),
    path('denuncia/', include('denuncia.urls', namespace="denuncia")),
    path('evento/', include('evento.urls', namespace="evento")),
    path('reputacion/', include('reputacion.urls', namespace="reputacion")),
    path('transaccion/', include('transaccion.urls', namespace="transaccion")),
    path('impinstagram/', include('impinstagram.urls', namespace="impinstagram")),


]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

evento/models.py
import datetime
from django.conf 	import settings
from django.db 		import models
from tienda.models 	import Producto


class Evento(models.Model):
	nombre 		= models.CharField(max_length=50)
	descripcion = models.CharField(max_length=500)
	flyer		= models.CharField(max_length=500)
	inicio 		= models.DateField()
	fin 		= models.DateField()


	def __str__(self):
		return self.nombre
	

evento/forms.py
from django.forms import ModelForm
from django import forms

from .models import Evento


class EventoForm(ModelForm):
	class Meta:
		model  = Evento
		fields = '__all__'
		widgets = {
            'inicio': forms.DateInput(attrs={'type': 'date'}),
			'fin': forms.DateInput(attrs={'type': 'date'})
		}

evento/views.py
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models    	import Evento
from .forms     	import EventoForm


class EventoList(ListView):
    model = Evento
    template_name = 'evento/list.html'    


class EventoDetail(DetailView):
    model = Evento
    template_name = 'evento/detail.html'    


class EventoCreation(CreateView):
    model = Evento
    success_url = reverse_lazy('evento:list')
    fields = ['nombre', 'inicio', 'fin','descripcion','flyer']
    template_name = 'evento/add.html'


class EventoUpdate(UpdateView):
    model = Evento
    success_url = reverse_lazy('evento:list')
    fields = ['nombre', 'inicio', 'fin','descripcion','flyer']
    template_name = 'evento/add.html'    


class EventoDelete(DeleteView):
    model = Evento
    success_url = reverse_lazy('evento:list')
    template_name = 'evento/confirm_delete.html'    
    

templates/evento/add.html
{% extends 'base/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}{% endblock %}
{% block content %}

<div class="mb-3">
	<h3>Completa el formulario</h3>
</div>

<form method="post">
    {% csrf_token %}
    {% for field in form.visible_fields %}
	 <div class="form-group">
	    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
	    {{ field|add_class:'form-control' }}
	    {% for error in field.errors %}
	    <div class="text-danger">{{ error }}</div>
	    {% endfor %}
	  </div>
  	{% endfor %}
    
    <button type="submit" class="btn btn-primary"> <i class="fas fa-plus"></i> 
    	Agregar</button>
</form>

{% endblock %}

templates/evento/confirm_delete.html
{% extends 'base/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}{% endblock %}
{% block content %}

<div class="mb-3">
	<h3>Completa el formulario</h3>
</div>

<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar el curso "{{ object }}"?
    <button type="submit" class="btn btn-danger"> <i class="fas fa-trash"></i> 
    	Eliminar</button>
</form>

{% endblock %}

templates/evento/detail.html
{% extends 'base/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}{% endblock %}
{% block content %}


<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{ evento.nombre }}</h5>
    <p class="card-text">{{ evento.descripcion }}</p>
    <p class="card-text">
    	{% language 'es' %}
    	<small class="text-muted">Inicio: {{ evento.inicio }} - Fin: {{ evento.fin }}</small>
    	{% endlanguage %}
    </p>
  </div>
  <img class="card-img-bottom" src="{{ evento.flyer }}" alt="Card image cap">
</div>

{% endblock %}

templates/evento/list.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}
<h3>{{ titulo }}</h3>


<a href="{% url 'evento:add' %}" type="button" class="btn btn-primary">
    <i class="fas fa-plus"></i> Agregar Evento</a>

<table class="table" style="margin-top: 1em">
    <tr>
        <thead class="thead-light">
            <tr>
                <th scope="col">Id</th>
            	<th scope="col">Nombre</th>
                <th scope="col">Inicio</th>
                <th scope="col">Fin</th>
                <th scope="col">Descripción</th>
                <th scope="col">Acción</th>                
            </tr>
        </thead>
        <tbody>
            {% for evento in object_list %}
            <tr>
                <td>
                    <a href="{% url 'evento:detail' evento.id %}">
                        {{evento.id}}
                    </a>
                </td>                
            	<td>{{evento.nombre}}</td>
                <td>{{evento.inicio}}</td>
                <td>{{evento.fin}}</td>
                <td>{{evento.descripcion}}</td>
				<td class="text-center">
                    <a href="{% url 'evento:detail' evento.id %}" class="btn btn-primary btn-sm"><i class="fa fa-eye" aria-hidden="true"></i>              
                    </a>                    <a href="{% url 'evento:edit' evento.id %}" class="btn btn-info btn-sm"><i class="fa fa-edit" aria-hidden="true"></i>              
                    </a>					
                    <a href="{% url 'evento:delete' evento.id %}" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i>              
					</a>
				</td>
            </tr>
            {% endfor %}
        </tbody>
</table>


{% endblock %}