cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	
	path("", views.get_cart, name="ver_carrito"),
	path("add/<product_id>/<quantity>/", views.add_to_cart, name="additem"),
	path("delete/<product_id>/", views.remove_from_cart, name="deleteitem"),

]

favs/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'favs'

urlpatterns = [
	
	#Productos favoritos
	path("p/list/", views.plist, name="plist"),
	path("p/<pid>/add/", views.padd, name="padd"),
	path("p/<pid>/remove/", views.premove, name="premove"),

	#Tiendas favoritas
	path("t/list/", views.tlist, name="tlist"),
	path("t/<tid>/add/", views.tadd, name="tadd"),
	path("t/<tid>/remove/", views.tremove, name="tremove"),	

]

movart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from core import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('messages/', include("pinax.messages.urls", namespace="pinax_messages")),
    path('', include('core.urls', namespace="core")),
    path('', include('tienda.urls', namespace="tienda")),
    path('cart/', include('cart.urls', namespace="carrito")),
    path('fav/', include('favs.urls', namespace="favs")),
    path('denuncia/', include('denuncia.urls', namespace="denuncia")),
    path('evento/', include('evento.urls', namespace="evento")),
    path('reputacion/', include('reputacion.urls', namespace="reputacion")),
    path('transaccion/', include('transaccion.urls', namespace="transaccion")),
    path('impinstagram/', include('impinstagram.urls', namespace="impinstagram")),


]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tienda/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .views import ProductoDeleteView


app_name = 'tienda'

urlpatterns = [
	
	path("tienda/add/", views.tiendadd, name="tiendadd"),
	path("tienda/list/", views.tiendalist, name="tiendalist"),
	path("tienda/ver/<tid>/", views.tiendaver, name="tiendaver"),
	path("tienda/<tid>/prods/", views.prodlist, name="prodlist"),
	path("prod/<pid>/ver/", views.prodver, name="prodver"),
	path("prod/add/<url>/<img>/", views.prodadd, name="prodadd"),
	path("prod/<pid>/edit/", views.prodedit, name="prodedit"),
	path("prod/list/", views.prodlistall, name="prodlistall"),
	path("prod/<pid>/cons/", views.prodcons, name="prodcons"),
	path('prod/<pk>/delete/', ProductoDeleteView.as_view(), name="proddelete"),

]

core/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Perfil(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) 
    url_profile_picture = models.CharField(max_length=500, default=None)
    domicilio 	= models.CharField(max_length=100, default=None, null=True)
    descripcion = models.CharField(max_length=250, default=None, null=True)
    telefono    = models.CharField(max_length=50, default=None, null=True)
    

tienda/models.py
from django.db import models
from django.conf import settings
from taggit.managers import TaggableManager


class Tienda(models.Model):
    usuario     = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,default=None) 
    estado      = models.PositiveIntegerField(default=1)

    def catalogo(self):
        return self.producto_set


class Producto(models.Model):
    tienda       = models.ForeignKey(Tienda, on_delete=models.CASCADE)
    nombre 	     = models.CharField(max_length=100)
    descripcion  = models.CharField(max_length=500)
    shortcode    = models.CharField(max_length=100)
    precio       = models.PositiveIntegerField()
    etiquetas    = TaggableManager()
    album        = models.BooleanField(default=False)
    visitas      = models.PositiveIntegerField(default=1)   

    class Meta:
        unique_together = ('tienda', 'shortcode')

    def visita(self):
        self.visitas += 1
        self.save()

    def save_album(self, urls):
        for url in urls:
            try:
                i = Imagen(producto=self, url=url)
                i.save()
            except Exception as e:
                raise e

    #def get_album(self):
                    


class Imagen(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    url = models.CharField(max_length=300)
    

favs/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from fav.models import Favorite
from tienda.models import Tienda, Producto
from django.contrib.auth.decorators import login_required


@login_required
def plist(request):
	favs = Favorite.objects.for_user(request.user, model=Producto)
	t 	 = 'Productos favoritos'
	return render(request, 'favs/plist.html', {'favs' : favs, 'titulo': t})


@login_required
def padd(request, pid):
	try:
		prod = Producto.objects.get(id=pid)
		fav = Favorite.objects.create(request.user, prod)
		fav.save()
		messages.success(request, 'Se ha agregado a favoritos!')
	except Exception as e:
		messages.error(request, 'Ha ocurrido un error, intente de nuevo por favor')
	url = request.META.get('HTTP_REFERER')
	return redirect(url)


@login_required
def premove(request, pid):
	try:
		prod = Producto.objects.get(id=pid)
		fav = Favorite.objects.get_favorite(request.user, prod)
		fav.delete()
		messages.warning(request, 'Se ha eliminado de favoritos!')
	except Exception as e:
		messages.error(request, 'Ha ocurrido un error, intente de nuevo por favor')
	url = request.META.get('HTTP_REFERER')
	return redirect(url)


@login_required
def tlist(request):
	favs = Favorite.objects.for_user(request.user, model=Tienda)
	return render(request, 'favs/tlist.html', {'favs' : favs})


@login_required
def tadd(request, tid):
	try:
		tienda = Tienda.objects.get(id=tid)
		fav = Favorite.objects.create(request.user, tienda)
		fav.save()
		messages.success(request, 'Se ha agregado a favoritos!')
	except Exception as e:
		messages.error(request, 'Ha ocurrido un error, intente de nuevo por favor')
	url = request.META.get('HTTP_REFERER')
	return redirect(url)


@login_required
def tremove(request, tid):
	try:
		tienda = Tienda.objects.get(id=tid)
		fav = Favorite.objects.get_favorite(request.user, tienda)
		fav.delete()
		messages.warning(request, 'Se ha eliminado de favoritos!')
	except Exception as e:
		messages.error(request, 'Ha ocurrido un error, intente de nuevo por favor')
	url = request.META.get('HTTP_REFERER')
	return redirect(url)

templates/favs/plist.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}
<h3>{{ titulo }}</h3>

<div class="row">
{% for fav in favs %}
{% include 'favs/prodcard.html' with producto=fav.target %}
{% empty %}
	no hay favoritos
{% endfor %}
</div>
{% endblock %}

{% block scripts %}
	{{ block.super }}
	{% for fav in favs %}
	<script type="text/javascript">
	$.ajax({
	    type: 'GET',
	    url: "https://www.instagram.com/p/{{fav.target.shortcode}}/?__a=1",
	    error: function () {
	    },
	    success: function (data) {
		    media = data.graphql.shortcode_media
		    document.getElementById('img-{{fav.target.id}}').src = media.display_url;
	    }
	});
	</script>
	{% endfor %}
{% endblock %}

templates/favs/prodcard.html
{% load static %}
<div class="col-md-4 col-lg-3 px-2 mb-3">
	<div class="product-card card">
	    <div class="card-body">
	        <span class="text-secondary small text-uppercase"></span>
	        <h3 class="h6 mb-2 font-weight-bold text-uppercase">{{ producto.nombre }}</h3>
	        <div class="d-flex">
	            <h4 class="h5 w-50 font-weight-bold color-bordo">${{ producto.precio }}</h4>    
	            <div class="w-50 text-right">
	            	<a href="{% url 'favs:premove' producto.id %}">
	                <i class="fa fa-heart text-danger fa-2x" aria-hidden="true"></i>
	                </a>
	            </div>
	        </div>
	        <!--<img class="w-100 mt-2 mb-3" src="{{ producto.imagen_set.all.0.url }}" />-->
{% with 'img/'|add:producto.tienda.usuario.username|add:'/'|add:producto.imagen_set.all.0.url as image_static %}
<img id="img-{{producto.id}}" class="w-100 mt-2 mb-3 rounded" src="{% static image_static %}" />
{% endwith %}
	        <a href="{% url 'tienda:prodver' producto.id %}" class="btn btn-outline-warning btn-block mb-2 rounded-pill">
	            <i class="fa fa-eye"></i> Ver
	        </a>		        
	    </div>
	</div>
</div>

templates/favs/tlist.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}
<h3>{{ titulo }}</h3>

<div class="comprar container">
	<h3>Tiendas Favoritas</h3></br>

	<div class="row">
	{% for fav in favs %}
	<div class="col-md-4 col-sm-6 col-xs-12">
	    <div class="card mb-3">
	        <div class="card-body text-center">
	            <p><img class="img-fluid w-50 rounded-circle" src="{{ fav.target.usuario.perfil_set.all.0.url_profile_picture }}" alt="card image"></p>
	            <h4 class="card-title">{{ fav.target.usuario.username }}</h4>
	            <a href="{% url 'tienda:prodlist' fav.target.id %}" class="btn btn-warning btn-sm"><i class="fa fa-rocket"></i></a>
	            <a href="{% url 'favs:tremove' fav.target.id %}"><i class="fa fa-star fa-2x text-warning"></i></a>	            
	        </div>
	    </div>
	</div>		
	{% empty %}
		No hay favoritos
	{% endfor %}

	</div>
</div>

{% endblock %}